# Generated by Django 3.2.18 on 2023-06-02 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Thị Trấn', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tên Thị Trấn', help_text='Tên Thị Trấn', max_length=1024)),
                ('code', models.CharField(help_text='code Thị Trấn', max_length=1024, unique=True)),
                ('division_type', models.CharField(help_text='loại thị trấn', max_length=1024)),
                ('codename', models.CharField(help_text='Codename Thị Trấn', max_length=1024)),
                ('ditrict_code', models.CharField(help_text='Code quận/huyện', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemgeneraldirectorymanagement_ward_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemgeneraldirectorymanagement_ward_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Thị Trấn',
                'verbose_name_plural': 'Thị Trấn',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Tỉnh', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Xã', help_text='Tên Tỉnh', max_length=1024)),
                ('code', models.CharField(help_text='Code Tỉnh', max_length=1024, unique=True)),
                ('codename', models.CharField(help_text='Codename Tỉnh', max_length=1024)),
                ('division_type', models.CharField(help_text='loại', max_length=1024)),
                ('phone_code', models.CharField(help_text=' Số ', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemgeneraldirectorymanagement_province_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemgeneraldirectorymanagement_province_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Xã',
                'verbose_name_plural': 'Xã',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id quận/huyện', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Huyện', help_text='Tên quận/huyện', max_length=1024)),
                ('code', models.CharField(help_text='Code huyện', max_length=1024, unique=True)),
                ('division_type', models.CharField(help_text='loại quận/huyện', max_length=1024)),
                ('codename', models.CharField(help_text='Codename quận/huyện', max_length=1024)),
                ('province_code', models.CharField(help_text='Code tỉnh/thành phộ', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemgeneraldirectorymanagement_districts_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemgeneraldirectorymanagement_districts_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Huyện',
                'verbose_name_plural': 'Huyện',
            },
        ),
    ]
