# Generated by Django 3.2.18 on 2023-06-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemGeneralDirectoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Thuộc Thành Phố', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SystemGeneralDirectoryManagement.province'),
        ),
        migrations.AddField(
            model_name='ward',
            name='districts',
            field=models.ForeignKey(blank=True, help_text='Thuộc Huyện', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SystemGeneralDirectoryManagement.districts'),
        ),
    ]
