# Generated by Django 3.2.18 on 2023-05-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_staffinformation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinformation',
            name='company',
            field=models.ForeignKey(help_text='Thuộc Công ty', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='staffinformation',
            name='position',
            field=models.ForeignKey(help_text='Thuộc Phòng', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.position'),
        ),
        migrations.AddField(
            model_name='staffinformation',
            name='unit',
            field=models.ForeignKey(help_text='Thuộc Đơn Vị', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.unit'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(help_text='Thuộc Công ty', on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(help_text='Thuộc Phòng', on_delete=django.db.models.deletion.CASCADE, to='company.position'),
        ),
    ]
