# Generated by Django 3.2.18 on 2023-05-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_staffinformation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(help_text='Số Điện Thoại liên Hệ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='staffinformation',
            name='phone_number',
            field=models.CharField(help_text='Số điện thoại', max_length=1024),
        ),
    ]
