# Generated by Django 3.2.18 on 2023-05-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20230530_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(help_text='Mã Chức Vụ', max_length=1024, null=True, unique=True),
        ),
    ]
