# Generated by Django 3.2.18 on 2023-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(help_text='Mã phòng', max_length=1024, null=True, unique=True),
        ),
    ]
