# Generated by Django 3.2.10 on 2023-05-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price_buy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Giá mua', max_digits=30, null=True),
        ),
    ]
