# Generated by Django 3.2.10 on 2023-05-05 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0007_alter_asset_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateField(default=datetime.date, help_text='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateField(default=datetime.date, editable=False, help_text='Cập nhật lúc'),
        ),
    ]
