# Generated by Django 3.2.10 on 2023-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0009_auto_20230505_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetail',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetdetailtemplate',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetoftype',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='ownstatus',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='unitcategory',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='warehousecategory',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
    ]
