# Generated by Django 3.2.10 on 2023-05-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0010_auto_20230505_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateField(auto_now=True, help_text='Ngày mua'),
        ),
    ]
