# Generated by Django 3.2.18 on 2023-06-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemGeneralDirectoryManagement', '0002_auto_20230602_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Tỉnh', 'verbose_name_plural': 'Tỉnh'},
        ),
    ]
