# Generated by Django 3.2.10 on 2023-05-05 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0002_alter_asset_price_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetdetail',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetdetailtemplate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetoftype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='ownstatus',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='unitcategory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='warehousecategory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
    ]
