# Generated by Django 3.2.10 on 2023-05-05 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0004_alter_asset_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Ngày mua'),
        ),
    ]
