# Generated by Django 3.2.10 on 2023-05-05 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0006_alter_asset_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='Cập nhật lúc'),
        ),
    ]
