# Generated by Django 3.2.10 on 2023-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0008_auto_20230505_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateField(auto_now_add=True, help_text='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateField(auto_now_add=True, help_text='Cập nhật lúc'),
        ),
    ]
