# Generated by Django 3.2.10 on 2023-05-11 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0011_alter_asset_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateField(default=datetime.date.today, help_text='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Kho', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetmanagement_asset_warehouse', to='AssetManagement.warehousecategory'),
        ),
    ]
