# Generated by Django 3.2.10 on 2023-05-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0012_auto_20230511_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(blank=True, help_text='Tên của Nam', max_length=150, null=True),
        ),
    ]
