# Generated by Django 3.2.10 on 2023-05-26 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssetManagement', '0013_asset_asset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Khóa chính của đơn vị tiền tệ', primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(help_text='Mã đơn vị tiền tệ', max_length=150, unique=True)),
                ('name', models.CharField(blank=True, help_text='Tên đơn vị tiền tệ', max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Được tạo lúc')),
                ('updated_at', models.DateField(auto_now_add=True, help_text='Cập nhật lúc')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Được tạo bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetmanagement_currencyunit_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetmanagement_currencyunit_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Đơn vị tiền tệ',
                'verbose_name_plural': 'Những đơn vị tiền tệ',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='currency_unit',
            field=models.ForeignKey(blank=True, help_text='Đơn vị tiền tệ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetmanagement_asset_currency', to='AssetManagement.currencyunit'),
        ),
    ]
