# Generated by Django 3.2.18 on 2023-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': 'Nhóm Quyền ', 'verbose_name_plural': 'Nhóm Quyền'},
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='desc',
            field=models.TextField(blank=True, help_text='Mô tả', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='desc',
            field=models.TextField(blank=True, help_text='Mô tả', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='modelspermission',
            name='name',
            field=models.CharField(help_text='Tên Model Name', max_length=100),
        ),
    ]
