# Generated by Django 3.2.18 on 2023-05-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0002_auto_20230517_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='account_text',
            field=models.CharField(help_text='Tên Quyền', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions_text',
            field=models.CharField(help_text='Tên Quyền', max_length=10000, null=True),
        ),
    ]
