# Generated by Django 3.2.18 on 2023-05-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0003_auto_20230519_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='account_text',
            field=models.CharField(blank=True, help_text='Tên Account', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='permissions_text',
            field=models.CharField(blank=True, help_text='Tên Quyền', max_length=10000, null=True),
        ),
    ]
