# Generated by Django 3.2.18 on 2023-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0004_auto_20230519_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='account_text',
            field=models.CharField(blank=True, help_text='Tên Account', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='permissions_group_text',
            field=models.CharField(blank=True, help_text='Tên Quyền', max_length=10000, null=True),
        ),
    ]
