# Generated by Django 3.2.18 on 2023-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0009_auto_20230525_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelspermission',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Model'},
        ),
        migrations.AddField(
            model_name='modelspermission',
            name='app',
            field=models.CharField(help_text='Tên App', max_length=100, null=True),
        ),
    ]
