# Generated by Django 3.2.18 on 2023-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0010_auto_20230525_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='perm_usergroup_permissions', to='Perm.Permission'),
        ),
    ]
