# Generated by Django 3.2.10 on 2023-04-28 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Depreciation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='assetrevaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetrevaluation_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='depreciationassetdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciationassetdetail_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='depreciationdetail',
            name='aset',
            field=models.OneToOneField(blank=True, help_text='TÀI SẢN1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='AssetManagement.asset'),
        ),
        migrations.AlterField(
            model_name='depreciationdetail',
            name='depreciation_value',
            field=models.IntegerField(blank=True, editable=False, help_text=' Giá trị để khấu hao', null=True),
        ),
        migrations.AlterField(
            model_name='depreciationdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciationdetail_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='depreciationperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciationperiod_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='depreciationtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciationtype_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='yearviews',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearviews_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
