# Generated by Django 3.2.10 on 2023-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0005_alter_depreciationdetail_date_been_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationtype',
            name='time',
            field=models.IntegerField(blank=True, help_text=' Thời gian sua doi ', null=True),
        ),
    ]
