# Generated by Django 3.2.10 on 2023-05-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0008_depreciationassetdetail_aet_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationassetdetail',
            name='value_end',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Giá trị cuối kỳ ', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='depreciationassetdetail',
            name='value_start',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Giá trị đầu kỳ', max_digits=30, null=True),
        ),
    ]
