# Generated by Django 3.2.10 on 2023-05-16 22:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Depreciation', '0014_auto_20230511_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDepreciationAssetDetail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False)),
                ('history_name', models.CharField(default='TÊN KHẤU HAO TÀI SẢN', help_text='TÊN KHẤU HAO TÀI SẢN', max_length=1024)),
                ('history_aet_depreciation', models.CharField(help_text='TÀI SẢN2', max_length=1024)),
                ('history_asset_depreciations', models.CharField(default='TÊN TÀI SẢN ', help_text='TTÊN TÀI SẢN', max_length=1024)),
                ('history_count_depreciation', models.IntegerField(blank=True, help_text=' Số lần khấu hao ', null=True)),
                ('history_days_depreciation', models.DateField(default=datetime.date.today, help_text='Thời điểm khấu hao')),
                ('history_value_start', models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Giá trị đầu kỳ', max_digits=30, null=True)),
                ('history_value_end', models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Giá trị cuối kỳ ', max_digits=30, null=True)),
                ('history_percent_depreciation', models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' % Khấu Hao ', max_digits=30, null=True)),
                ('history_value_depreciaiton', models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Giá trị Khấu Haos', max_digits=30, null=True)),
                ('history_remain_value', models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Giá trị còn lại ', max_digits=30, null=True)),
                ('history_yearviews', models.DateField(default=datetime.date.today, help_text='Thời điểm khấu hao')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Được tạo bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historydepreciationassetdetail_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historydepreciationassetdetail_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Lich Su Tài Sản Khấu Hao Chi Tiết',
                'verbose_name_plural': 'Những Lich Su Tài Sản Khấu Hao Chi Tiết',
            },
        ),
    ]
