# Generated by Django 3.2.10 on 2023-05-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0013_asset_asset_name'),
        ('Depreciation', '0015_historydepreciationassetdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrevaluation',
            name='asset_revaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_revaluation', to='AssetManagement.asset'),
        ),
    ]
