# Generated by Django 3.2.10 on 2023-05-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0004_auto_20230504_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationdetail',
            name='date_been_add',
            field=models.DateField(auto_now_add=True, help_text='Thời điểm khấu hao'),
        ),
    ]
