# Generated by Django 3.2.10 on 2023-05-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0006_alter_depreciationtype_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationdetail',
            name='type_depreciation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_depreciation', to='Depreciation.depreciationtype'),
        ),
    ]
