# Generated by Django 3.2.10 on 2023-05-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0010_auto_20230505_0722'),
        ('Depreciation', '0007_depreciationdetail_type_depreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationassetdetail',
            name='aet_depreciation',
            field=models.ForeignKey(blank=True, help_text='TÀI SẢN2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tai_san_depre', to='AssetManagement.asset'),
        ),
    ]
