# Generated by Django 3.2.10 on 2023-05-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0009_auto_20230509_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text=' Hệ số điều chỉnh ', max_digits=30, null=True),
        ),
    ]
