# Generated by Django 3.2.10 on 2023-05-10 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0012_depreciationassetdetail_yearviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationdetail',
            name='year_views',
            field=models.DateField(default=django.utils.timezone.now, help_text='Thời điểm khấu hao'),
        ),
    ]
