# Generated by Django 3.2.10 on 2023-05-21 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0016_assetrevaluation_asset_revaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationdetail',
            name='time_been_depreciation',
            field=models.DateField(default=datetime.date.today, help_text='Thời gian đã khấu hao'),
        ),
    ]
