# Generated by Django 3.2.10 on 2023-06-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0017_depreciationdetail_time_been_depreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationdetail',
            name='curency_change',
            field=models.CharField(default='TÊN KHẤU HAO', help_text='TÊN KHẤU HAO', max_length=1024),
        ),
    ]
