# Generated by Django 3.2.18 on 2023-05-16 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Acc', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên App', max_length=100)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_apppermission_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_apppermission_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='ModelsPermission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Model', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên App', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Mô tả', max_length=5000, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perm.apppermission')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_modelspermission_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_modelspermission_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id quyền', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên quyền', max_length=100)),
                ('is_add', models.BooleanField(default=False)),
                ('is_view_only', models.BooleanField(default=False)),
                ('is_view_all', models.BooleanField(default=False)),
                ('is_view_public', models.BooleanField(default=False)),
                ('is_delete_only', models.BooleanField(default=False)),
                ('is_delete_all', models.BooleanField(default=False)),
                ('is_delete_public', models.BooleanField(default=False)),
                ('is_edit_only', models.BooleanField(default=False)),
                ('is_edit_all', models.BooleanField(default=False)),
                ('is_edit_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_permission_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perm.modelspermission')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_permission_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Quyền',
                'verbose_name_plural': 'Quyền',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id ', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Nhóm quyền', help_text='Tên Nhóm Quyền', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('account', models.ManyToManyField(blank=True, related_name='perm_permissiongroup_account', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_permissiongroup_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('permissions', models.ManyToManyField(blank=True, related_name='perm_permissiongroup_permissions', to='Perm.Permission')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_permissiongroup_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Nhóm Người ',
                'verbose_name_plural': 'Nhóm Người',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid ', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Nhóm user', help_text='Tên nhóm user', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('account', models.ManyToManyField(blank=True, related_name='perm_usergroup_account', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_usergroup_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('permissions_group', models.ManyToManyField(blank=True, related_name='perm_usergroup_group_permissions', to='Perm.PermissionGroup')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_usergroup_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Nhóm Người ',
                'verbose_name_plural': 'Nhóm Người',
            },
        ),
    ]
