# Generated by Django 3.2.18 on 2023-05-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0005_auto_20230519_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'verbose_name': 'app', 'verbose_name_plural': 'Tên app`'},
        ),
        migrations.AlterModelOptions(
            name='modelspermission',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Tên Model'},
        ),
        migrations.AddField(
            model_name='permission',
            name='app_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Perm.apppermission'),
        ),
        migrations.AddField(
            model_name='permission',
            name='perm_name',
            field=models.CharField(help_text='Tên Full App/Model', max_length=500, null=True),
        ),
    ]
