# Generated by Django 3.2.18 on 2023-05-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0007_apppermission_stt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppermission',
            name='stt',
        ),
    ]
