# Generated by Django 3.2.18 on 2023-05-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perm', '0011_usergroup_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='model_id',
        ),
        migrations.AddField(
            model_name='permission',
            name='app',
            field=models.CharField(help_text='Tên App', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='model',
            field=models.CharField(help_text='Tên Model Name', max_length=100, null=True),
        ),
    ]
