# Generated by Django 3.2.10 on 2023-04-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Asset', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Asset name', max_length=1024, null=True)),
                ('code', models.CharField(help_text='Asset code', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_asset_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_asset_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='FormManagement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Asset', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Form name', max_length=1024, null=True)),
                ('code', models.CharField(help_text='Form code', max_length=1024, unique=True)),
                ('content', models.TextField(blank=True, help_text='Content', null=True)),
                ('execution_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Implementation date')),
                ('reason_asset_recovery', models.CharField(blank=True, help_text='Reason for Asset Recovery', max_length=1024, null=True)),
                ('loan_period', models.DateTimeField(blank=True, help_text='Loan Period', max_length=1024, null=True)),
                ('unit_currently_borrowing', models.CharField(blank=True, help_text='Unit Currently Browwing', max_length=1024, null=True)),
                ('buyer', models.CharField(blank=True, help_text='Buyer', max_length=1024, null=True)),
                ('price', models.FloatField(blank=True, help_text='Liquidation Price', max_length=1024, null=True)),
                ('liquidation_reason', models.CharField(blank=True, help_text='Lending Unit', max_length=1024, null=True)),
                ('lending_unit', models.CharField(blank=True, help_text='Lending Unit', max_length=1024, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_formmanagement_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Staff', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Staff name', max_length=1024, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_staff_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_staff_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ListTypeForm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Form type name', max_length=1024, null=True)),
                ('code', models.CharField(help_text='Form code', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_listtypeform_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_listtypeform_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ListAsset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code asset in list', max_length=1024, unique=True)),
                ('current_status_asset', models.CharField(blank=True, help_text='Current Status Asset', max_length=1024, null=True)),
                ('is_exits_when_inventory', models.BooleanField(blank=True, help_text='Does the asset exist at the time of the inventory?', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('code_form', models.ForeignKey(blank=True, help_text='Code Form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormManagement.formmanagement')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_listasset_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('name', models.ForeignKey(blank=True, help_text='Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormManagement.asset')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_listasset_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='staff_confiscated_asset',
            field=models.ForeignKey(blank=True, help_text='Staff Confiscated Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormManagement.staff'),
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='staff_receive_property',
            field=models.ForeignKey(blank=True, help_text='Staff Receive Property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_receive_property', to='FormManagement.staff'),
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='type_form',
            field=models.ForeignKey(blank=True, help_text='Name Type Form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormManagement.listtypeform'),
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_formmanagement_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
