# Generated by Django 3.2.10 on 2023-05-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormManagement', '0002_auto_20230428_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmanagement',
            name='execution_date',
            field=models.DateField(blank=True, default='2023-05-05', help_text='Implementation date'),
        ),
    ]
