# Generated by Django 3.2.10 on 2023-05-06 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('AssetManagement', '0010_auto_20230505_0722'),
        ('FormManagement', '0006_auto_20230506_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='listasset',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetManagement.asset'),
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='delivered',
            field=models.ForeignKey(blank=True, help_text='Delivered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered', to='company.staff'),
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='received',
            field=models.ForeignKey(blank=True, help_text='Received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to='company.staff'),
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='staff_confiscated_asset',
            field=models.ForeignKey(blank=True, help_text='Staff Confiscated Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_confiscated_asset', to='company.staff'),
        ),
        migrations.AlterField(
            model_name='listasset',
            name='name',
            field=models.CharField(default='Tài sản của phiếu', help_text='Name', max_length=1024),
        ),
        migrations.CreateModel(
            name='HistoryUseAsset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code', max_length=1024, unique=True)),
                ('name', models.CharField(default='Quá trình sử dụng', help_text='Name', max_length=1024)),
                ('status_current', models.CharField(blank=True, help_text='Status Current', max_length=1024, null=True)),
                ('started_using', models.DateTimeField(blank=True, help_text='End Use', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('asset', models.ForeignKey(blank=True, help_text='Asset', null=True, on_delete=django.db.models.deletion.PROTECT, to='AssetManagement.asset')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_historyuseasset_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_historyuseasset_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.PROTECT, to='company.staff')),
            ],
        ),
    ]
