# Generated by Django 3.2.10 on 2023-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormManagement', '0011_auto_20230521_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmanagement',
            name='status',
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
