# Generated by Django 3.2.10 on 2023-05-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FormManagement', '0013_auto_20230523_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Mã Loại Hành Động', max_length=1024, unique=True)),
                ('name', models.CharField(default='Tên Loại Hành Động', help_text='Name', max_length=1024)),
                ('color_code', models.CharField(help_text='Color', max_length=1024, unique=True)),
                ('icon', models.CharField(help_text='Icon', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_typeaction_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('type_form', models.ForeignKey(blank=True, help_text='Name Type Form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormManagement.listtypeform')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formmanagement_typeaction_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='historyuseasset',
            name='type_action',
            field=models.ForeignKey(blank=True, help_text='Asset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.typeaction'),
        ),
    ]
