# Generated by Django 3.2.10 on 2023-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormManagement', '0014_auto_20230523_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeaction',
            name='color_code',
            field=models.CharField(blank=True, help_text='Color', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='typeaction',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon', max_length=1024, null=True),
        ),
    ]
