# Generated by Django 3.2.10 on 2023-04-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên danh sách', max_length=1024)),
                ('code', models.CharField(help_text='Mã danh sách', max_length=1024, unique=True)),
                ('time', models.CharField(blank=True, default='2023-04-27, 19:13:35', help_text='Ghi chú thời gian để có thể sử dụng lại khi cần', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm đăng tải')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_assetlist_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_assetlist_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Danh sách tài sản',
                'verbose_name_plural': 'Danh sách tài sản',
            },
        ),
        migrations.CreateModel(
            name='ProposalFormType',
            fields=[
                ('name', models.CharField(blank=True, default='Đơn đề xuất', help_text='Kiểu đơn', max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Mã kiểu đơn', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformtype_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformtype_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Kiểu đơn',
                'verbose_name_plural': 'Kiểu đơn',
            },
        ),
        migrations.CreateModel(
            name='ProposalFormStatus',
            fields=[
                ('name', models.CharField(blank=True, help_text='Hiệu lực đơn đề xuất', max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Mã trạng thái', max_length=1024, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm đăng tải')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformstatus_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformstatus_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Trạng thái',
                'verbose_name_plural': 'Trạng thái',
            },
        ),
        migrations.CreateModel(
            name='ProposalForm',
            fields=[
                ('name', models.CharField(blank=True, help_text='Đơn đề xuất', max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Mã đơn', max_length=1024, unique=True)),
                ('reason', models.CharField(help_text='Lý do tạo đơn', max_length=10024)),
                ('price', models.CharField(blank=True, help_text='Giá', max_length=10024, null=True)),
                ('buyer', models.CharField(blank=True, help_text='Người mua', max_length=10024, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset_list', models.ForeignKey(help_text='Danh sách tài sản', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProposalForm.assetlist')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('proposal_status', models.ForeignKey(help_text='Hiệu lực', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProposalForm.proposalformstatus')),
                ('proposal_type', models.ForeignKey(help_text='Kiểu đơn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProposalForm.proposalformtype')),
                ('proposer', models.ForeignKey(help_text='Người tạo đơn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.staff')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Đơn đề xuất',
                'verbose_name_plural': 'Đơn đề xuất',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalForm.assetlist')),
            ],
        ),
    ]
