# Generated by Django 3.2.18 on 2023-05-22 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProposalForm', '0002_remove_assetlist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_assetlist_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_assetlist_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformstatus_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformstatus_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformtype_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformtype_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
