# Generated by Django 3.2.10 on 2023-05-18 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_staffinformation_avatar'),
        ('ProposalForm', '0002_remove_assetlist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalformtype',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('price', 'Giá thanh lý'), ('buyer', 'Người mua')], help_text='Lựa chọn trường cho loại đơn', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm đăng tải'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_assetlist_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_assetlist_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='proposer',
            field=models.ForeignKey(help_text='Người đề xuất', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.staff'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm đăng tải'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformstatus_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='proposalformstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformstatus_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformtype_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='proposalformtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalformtype_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
