# Generated by Django 3.2.10 on 2023-05-22 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_staffinformation_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssetManagement', '0013_asset_asset_name'),
        ('ProposalForm', '0003_auto_20230518_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalform',
            name='delivered',
            field=models.ForeignKey(blank=True, help_text='Delivered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_delivered', to='company.staff'),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='execution_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Implementation date'),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='lending_unit',
            field=models.ForeignKey(blank=True, help_text='Lending Unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_lending_unit', to='company.unit'),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='liquidation_reason',
            field=models.CharField(blank=True, help_text='Lending Unit', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='loan_period',
            field=models.DateTimeField(blank=True, help_text='Loan Period', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='reason_asset_recovery',
            field=models.CharField(blank=True, help_text='Reason for Asset Recovery', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='received',
            field=models.ForeignKey(blank=True, help_text='Received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_received', to='company.staff'),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='staff_confiscated_asset',
            field=models.ForeignKey(blank=True, help_text='Staff Confiscated Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_staff_confiscated_asset', to='company.staff'),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='staff_receive_property',
            field=models.ForeignKey(blank=True, help_text='Staff Receive Property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_staff_receive_property', to='company.staff'),
        ),
        migrations.AddField(
            model_name='proposalform',
            name='unit_currently_borrowing',
            field=models.ForeignKey(blank=True, help_text='Unit Currently Browwing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_proposalform_unit_currently_borrowing', to='company.unit'),
        ),
        migrations.AlterField(
            model_name='list',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetManagement.asset'),
        ),
        migrations.AlterField(
            model_name='list',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProposalForm.assetlist'),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='buyer',
            field=models.CharField(blank=True, help_text='Buyer', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='price',
            field=models.FloatField(blank=True, help_text='Liquidation Price', max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='ListType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Form type name', max_length=1024, null=True)),
                ('code', models.CharField(help_text='Form code', max_length=1024, unique=True)),
                ('fields', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('name', 'Tên'), ('code', 'Mã'), ('execution_date', 'Ngày thực hiện'), ('attached_document', 'Đơn đi kèm'), ('delivered', 'Họ tên người giao'), ('received', 'Họ tên người nhận'), ('staff_receive_property', 'Nhân viên nhận tài sản được cấp'), ('staff_confiscated_asset', 'Nhân viên bị thu hồi tài sản'), ('reason_asset_recovery', 'Lý do bị thu hồi tài sản'), ('loan_period', 'Thời gian mượn đến'), ('lending_unit', 'Đơn vị cho mượn'), ('unit_currently_borrowing', 'Đơn vị đang mượn'), ('warehouse', 'Kho'), ('suplier', 'Nhà cung cấp'), ('buyer', 'Người mua'), ('price', 'Giá'), ('liquidation_reason', 'Lý do thanh lý'), ('created_by', 'Người tạo'), ('updated_by', 'Người chỉnh sửa'), ('updated_at', 'Ngày chỉnh sửa'), ('created_at', 'Ngày tạo')], help_text='Lựa chọn trường cho loại phiếu', max_length=273, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Update time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Posting time')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_listtype_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposalform_listtype_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AlterField(
            model_name='proposalform',
            name='proposal_type',
            field=models.ForeignKey(help_text='Kiểu đơn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProposalForm.listtype'),
        ),
    ]
