# Generated by Django 3.2.10 on 2023-04-28 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('AssetManagement', '0001_initial'),
        ('FormManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='staff_confiscated_asset',
            field=models.ForeignKey(blank=True, help_text='Staff Confiscated Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.staff'),
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='staff_receive_property',
            field=models.ForeignKey(blank=True, help_text='Staff Receive Property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_receive_property', to='company.staff'),
        ),
        migrations.AlterField(
            model_name='listasset',
            name='name',
            field=models.ForeignKey(blank=True, help_text='Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetManagement.asset'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
