# Generated by Django 3.2.10 on 2023-05-06 02:25

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('ProposalForm', '0002_alter_assetlist_time'),
        ('ProposalForm', '0001_initial'),
        ('FormManagement', '0005_alter_formmanagement_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmanagement',
            name='attached_document',
            field=models.ForeignKey(blank=True, help_text='Attached Document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProposalForm.proposalform'),
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='delivered',
            field=models.CharField(blank=True, help_text='Delivered', max_length=1024, null=True, verbose_name=company.models.Staff),
        ),
        migrations.AddField(
            model_name='formmanagement',
            name='received',
            field=models.CharField(blank=True, help_text='Received', max_length=1024, null=True, verbose_name=company.models.Staff),
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='lending_unit',
            field=models.CharField(blank=True, help_text='Lending Unit', max_length=1024, null=True, verbose_name=company.models.Unit),
        ),
        migrations.AlterField(
            model_name='formmanagement',
            name='unit_currently_borrowing',
            field=models.CharField(blank=True, help_text='Unit Currently Browwing', max_length=1024, null=True, verbose_name=company.models.Unit),
        ),
        migrations.AlterField(
            model_name='listasset',
            name='code_form',
            field=models.ForeignKey(blank=True, help_text='Code Form', null=True, on_delete=django.db.models.deletion.CASCADE, to='FormManagement.formmanagement'),
        ),
    ]
