# Generated by Django 3.2.10 on 2023-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormManagement', '0010_auto_20230511_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmanagement',
            name='status',
            field=models.CharField(choices=[('confirm', 'Xác nhận'), ('no_confirm', 'Không xác nhận')], default='no_confirm', help_text='Xác nhận phiếu', max_length=64),
        ),
        migrations.AddField(
            model_name='historyuseasset',
            name='form',
            field=models.CharField(blank=True, help_text='Phiếu', max_length=1024, null=True),
        ),
    ]
