# Generated by Django 3.2.10 on 2023-05-31 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0014_auto_20230526_0410'),
        ('company', '0003_auto_20230525_1127'),
        ('FormManagement', '0017_auto_20230526_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmanagement',
            name='type_form',
            field=models.ForeignKey(blank=True, help_text='Name Type Form', null=True, on_delete=django.db.models.deletion.CASCADE, to='FormManagement.listtypeform'),
        ),
        migrations.AlterField(
            model_name='historyuseasset',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset', null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset'),
        ),
        migrations.AlterField(
            model_name='historyuseasset',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.staff'),
        ),
        migrations.AlterField(
            model_name='typeaction',
            name='type_form',
            field=models.ForeignKey(blank=True, help_text='Name Type Form', null=True, on_delete=django.db.models.deletion.CASCADE, to='FormManagement.listtypeform'),
        ),
    ]
