# Generated by Django 3.2.10 on 2023-05-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlist',
            name='time',
        ),
    ]
