# Generated by Django 3.2.10 on 2023-05-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalForm', '0003_auto_20230522_0207'),
        ('ProposalForm', '0004_auto_20230522_1101'),
    ]

    operations = [
    ]
