# Generated by Django 3.2.10 on 2023-05-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalForm', '0005_auto_20230523_1751'),
        ('ProposalForm', '0005_merge_0003_auto_20230522_0207_0004_auto_20230522_1101'),
    ]

    operations = [
    ]
