# Generated by Django 3.2.10 on 2023-04-27 12:14

from django.db import migrations, models
import django.utils.timezone
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2048, null=True)),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('owner_tndid', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('ipv4', netfields.fields.CidrAddressField(blank=True, default=None, max_length=43, null=True)),
                ('app_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('class_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('func_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
