# Generated by Django 3.2.10 on 2023-04-27 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Thành Phố', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Xã', help_text='Tên Thành Phố', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
            ],
            options={
                'verbose_name': 'Thành Phố ',
                'verbose_name_plural': 'Thành Phố',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Xã', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Xã', help_text='Tên Xã', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_commune_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_commune_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Xã',
                'verbose_name_plural': 'Xã',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Công Ty', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tên Công Ty', help_text='Tên Công Ty', max_length=1024)),
                ('code_company', models.CharField(default='Mã Công Ty', help_text='Mã Công Ty', max_length=1024, unique=True)),
                ('address', models.CharField(default='Địa chỉ cụ thể', max_length=1024)),
                ('tax_code', models.CharField(default='Mã Số Thuế', help_text='Mã Số Thuế', max_length=1024, unique=True)),
                ('phone_number', models.CharField(default='Số Điện Thoại Liên Hệ', help_text='Số Điện Thoại liên Hệ', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('city', models.ForeignKey(help_text='Thuộc Thành Phố', on_delete=django.db.models.deletion.CASCADE, to='company.city')),
                ('commune', models.ForeignKey(help_text='Thuộc Xã', on_delete=django.db.models.deletion.CASCADE, to='company.commune')),
            ],
            options={
                'verbose_name': 'Công Ty',
                'verbose_name_plural': 'Công Ty',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Huyện', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Huyện', help_text='Tên Huyện', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('commune', models.ForeignKey(help_text='Thuộc Xã', on_delete=django.db.models.deletion.CASCADE, to='company.commune')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_district_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_district_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Huyện',
                'verbose_name_plural': 'Huyện',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Chức Vụ', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Chức Vụ', help_text='Tên Chức Vụ', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_position_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Chức Vụ',
                'verbose_name_plural': 'Chức vụ',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Thông Tin', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tên Nhân Viên', help_text='Tên Nhân Viên', max_length=1024)),
                ('code', models.CharField(default='MÃ Nhân Viên', help_text='MÃ Nhân Viên', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('company', models.ForeignKey(help_text='Thuộc Đơn Vị', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staff_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('position', models.ForeignKey(help_text='Thuộc Đơn Vị', on_delete=django.db.models.deletion.CASCADE, to='company.position')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Đơn Vị', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Đơn Vị', help_text='Tên Đơn Vị', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('company', models.ForeignKey(help_text='Thuộc Công Ty', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_unit_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_unit_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Đơn Vị',
                'verbose_name_plural': 'Đơn Vị',
            },
        ),
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Trạng Thái', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tên Trạng Thái', help_text='Tên Trạng Thái', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staffstatus_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staffstatus_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Trạng Thái Nhân Viên',
                'verbose_name_plural': 'Trạng Thái Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='StaffInformation',
            fields=[
                ('full_name', models.CharField(default='Họ Và Tên', help_text='Họ Và Tên', max_length=1024)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Thông Tin', primary_key=True, serialize=False)),
                ('email', models.CharField(default='email Nhân Viên', help_text='email Nhân Viên', max_length=1024)),
                ('id_card', models.CharField(default='Chứng Minh Thư', help_text='Chứng Minh Thư', max_length=1024)),
                ('degree', models.FileField(blank=True, default='Bằng cấp', help_text='Bằng cấp', max_length=1024, null=True, upload_to=None)),
                ('phone_number', models.CharField(default='Số điện thoại', help_text='Số điện thoại', max_length=1024)),
                ('address', models.CharField(default='Địa chỉ cụ thể', max_length=1024)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('city', models.ForeignKey(blank=True, help_text='Thuộc Thành Phố', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.city')),
                ('commune', models.ForeignKey(blank=True, help_text='Thuộc Xã', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.commune')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staffinformation_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('district', models.ForeignKey(blank=True, help_text='Thuộc Huyện', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.district')),
                ('staff', models.ForeignKey(help_text='Tên Nhân Viên', on_delete=django.db.models.deletion.CASCADE, to='company.staff')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staffinformation_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Thông Tin Nhân Viên',
                'verbose_name_plural': 'Thông Tin Nhân Viên',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='staffstatus',
            field=models.ForeignKey(blank=True, help_text='Trạng Thái Nhân Viên', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.staffstatus'),
        ),
        migrations.AddField(
            model_name='staff',
            name='unit',
            field=models.ForeignKey(help_text='Thuộc Đơn Vị', on_delete=django.db.models.deletion.CASCADE, to='company.unit'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staff_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(help_text='Thuộc Đơn Vị', on_delete=django.db.models.deletion.CASCADE, to='company.unit'),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_position_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id Tình Trạng', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tình Trạng', help_text='Tên Tình Trạng', max_length=1024)),
                ('code', models.CharField(default=' MÃ Tình Trạng', help_text='MÃ Tình Trạng', max_length=1024, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_companystatus_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_companystatus_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Tình trạng công ty',
                'verbose_name_plural': 'Tình trạng công Ty',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='companystatus',
            field=models.ForeignKey(blank=True, help_text='Trạng Thái Công Ty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companystatus'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_company_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Thuộc Huyện', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.district'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_company_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='city',
            name='commune',
            field=models.ForeignKey(help_text='Thuộc Xã', on_delete=django.db.models.deletion.CASCADE, to='company.commune'),
        ),
        migrations.AddField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_city_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Thuộc Huyện', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.district'),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_city_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
