# Generated by Django 3.2.18 on 2023-05-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinformation',
            name='avatar',
            field=models.ImageField(blank=True, default='company/default-avatar.jpg', max_length=4096, null=True, upload_to='avatar-images/%Y/%m/%d/'),
        ),
    ]
