# Generated by Django 3.2.18 on 2023-05-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230530_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinformation',
            name='address',
            field=models.CharField(max_length=1024),
        ),
    ]
