# Generated by Django 3.2.18 on 2023-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_position_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(help_text='Mã Chức Vụ', max_length=1024, null=True, unique=True),
        ),
    ]
