# Generated by Django 3.2.10 on 2023-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecode',
            name='app_name',
            field=models.CharField(blank=True, default='app_name', help_text='app_name', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='company_code',
            field=models.CharField(blank=True, default='Company_Code', help_text='Company_Code', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='current_code',
            field=models.CharField(blank=True, default='current_code', help_text='current_code', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='length_code',
            field=models.CharField(blank=True, default='length_code', help_text='length_code', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='mode_name',
            field=models.CharField(blank=True, default='mode_name', help_text='mode_name', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='prefix',
            field=models.CharField(blank=True, default='prefix', help_text='prefix', max_length=1024, null=True),
        ),
    ]
