# Generated by Django 3.2.10 on 2023-05-25 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0002_auto_20230525_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatecode',
            name='id',
        ),
        migrations.AddField(
            model_name='generatecode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='type_gen_code',
            field=models.IntegerField(blank=True, default=0, help_text='type_gen_code', null=True),
        ),
    ]
