# Generated by Django 3.2.10 on 2023-05-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='Company_Code', help_text='Company_Code', max_length=1024)),
                ('app_name', models.CharField(default='app_name', help_text='app_name', max_length=1024)),
                ('mode_name', models.CharField(default='mode_name', help_text='mode_name', max_length=1024)),
                ('prefix', models.CharField(default='prefix', help_text='prefix', max_length=1024)),
                ('length_code', models.CharField(default='length_code', help_text='length_code', max_length=1024)),
                ('current_code', models.CharField(default='current_code', help_text='current_code', max_length=1024)),
                ('type_gen_code', models.IntegerField(blank=True, help_text='type_gen_code', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm cập nhật')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày đăng tải')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Được tạo bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generatecode_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Cập nhật bởi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generatecode_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'CODE',
                'verbose_name_plural': 'NHỮNG CODE',
            },
        ),
    ]
