# Generated by Django 3.2.10 on 2023-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0008_alter_generatecode_current_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecode',
            name='company_code',
            field=models.CharField(blank=True, help_text='Company_Code', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='current_code',
            field=models.CharField(blank=True, help_text='current_code', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generatecode',
            name='length_code',
            field=models.CharField(blank=True, default='8', help_text='length_code', max_length=1024, null=True),
        ),
    ]
